### ISSUE TITLE
Login Screen 

### ISSUE THREAD

**Issue by RanchoDbest** [Lakhankumawat/smart-home-app#21] opened 2022-03-04 12:17 UTC
### Description

Hi, I would like to work on Login Screen. Please assign me this issue.  
![Screenshot 2022-03-04 at 4 50 47 PM](https://user-images.githubusercontent.com/12000313/156761963-aee1f2d4-2e60-4e6b-a75d-d04c64d237bd.png)

### Domain

UI/UX

### Type of Contribution

Addition

### Code of Conduct

- [X] I follow [Contributing Guidelines](https://github.com/Lakhankumawat/smart-home-app/blob/master/Contributing.md) & [Code of conduct](https://github.com/Lakhankumawat/smart-home-app/blob/master/.github/CODE_OF_CONDUCT.md) of Smart Home App.

**Comment by Lakhankumawat** [comment] 2022-03-04 14:29
Assigned to you make sure you follow code conventions and quality of code 🙃

**Comment by Chitrakshi2531** [comment] 2022-03-05 05:53
Hey @Lakhankumawat I wanted to work on this issue, Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant.

**Comment by Lakhankumawat** [comment] 2022-03-05 10:40
> Hey @Lakhankumawat I wanted to work on this issue, Please consider me next in the queue if the issue is not resolved. I'm a GSSOC22 participant.

ok

**Comment by Happ2y** [comment] 2022-03-06 06:14
I would also like to participate on this issue for **backend enhancements** if you allow me @Lakhankumawat @RanchoDbest.

**Comment by chandan0000** [comment] 2022-03-07 08:12
@Happ2y We will already design the UI after that you will see the back end.

**Comment by Happ2y** [comment] 2022-03-08 05:02
> @Happ2y We will already design the UI after that you will see the back end.

Okay, Let me know...

**Comment by Lakhankumawat** [comment] 2022-03-08 05:07
I would recommend the contributor of this issue to fetch upstream and resolve conflicts before creating a new Pull Request.

**Comment by Lakhankumawat** [comment] 2022-03-15 05:21
hi @RanchoDbest you have 4 more days and then issue will be assigned to someone else

**Comment by RanchoDbest** [comment] 2022-03-16 06:35
Sure I will do

**Closed** 2022-03-25 14:27 UTC
Labels: enhancement, help wanted, good first issue, design, develop, GSSoC22
